# Generated by Django 5.2 on 2025-04-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('salario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('fuente', models.CharField(max_length=50)),
                ('habilidades', models.ManyToManyField(to='analisis_mercado.habilidad')),
            ],
        ),
    ]
