# Generated by Django 5.2 on 2025-04-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_mercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='analisis_mercado.habilidad'),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
