# Generated by Django 5.1.6 on 2025-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_mercado', '0002_alter_habilidad_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='tipo_trabajo',
            field=models.CharField(default='No especificado', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='ofertaempleo',
            unique_together={('titulo', 'empresa')},
        ),
    ]
