# Generated by Django 5.1.6 on 2025-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_mercado', '0003_ofertaempleo_tipo_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='salario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='tipo_trabajo',
            field=models.CharField(default='No especificado', max_length=100),
        ),
    ]
