# Generated by Django 5.1.6 on 2025-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_mercado', '0005_alter_ofertaempleo_salario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaempleo',
            name='salario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
