# Generated by Django 5.2 on 2025-04-23 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_mercado', '0010_add_tendencia_to_habilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='experiencia_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='numero_postulantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='requisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='salario_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='salario_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='tipo_contrato',
            field=models.CharField(choices=[('indefinido', 'Indefinido'), ('temporal', 'Temporal'), ('practicas', 'Prácticas'), ('otro', 'Otro')], default='indefinido', max_length=20),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='fuente',
            field=models.CharField(choices=[('infojobs', 'InfoJobs'), ('tecnoempleo', 'Tecnoempleo'), ('linkedin', 'LinkedIn')], max_length=100),
        ),
        migrations.CreateModel(
            name='TendenciaMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('demanda', models.IntegerField()),
                ('postulaciones', models.IntegerField()),
                ('salario_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_mercado.habilidad')),
            ],
            options={
                'unique_together': {('habilidad', 'fecha')},
            },
        ),
    ]
