# Generated by Django 5.2 on 2025-04-23 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_mercado', '0011_ofertaempleo_activa_ofertaempleo_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('fecha_entrenamiento', models.DateTimeField()),
                ('metricas', models.JSONField()),
                ('parametros', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('demanda_predicha', models.IntegerField()),
                ('confianza', models.FloatField()),
                ('tendencia', models.FloatField()),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_mercado.habilidad')),
            ],
            options={
                'ordering': ['-fecha_prediccion', '-confianza'],
            },
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('razones', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_mercado.ofertaempleo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-puntuacion', '-fecha'],
            },
        ),
    ]
